sudo: false
language: node_js
node_js:
  - 8
before_install:
  - npm install elm
  - npm install elm-test@0.19.0-beta9

cache:
  directories:
    - elm-stuff/build-artifacts
    - node_modules

script:
  - elm-test
