sudo: false
language: node_js
node_js:
  - 8

before_install:
  - npm install npm@latest   
  - npm install elm@latest
  - npm install elm-test@beta

cache:
  directories:
    - elm-stuff/build-artifacts
    - node_modules

script:
  - travis_wait npm --verbose test
